version: "3"
services:
  todo-app:
    image: kixan123/todo-java-app
    container_name: todo-app
    ports:
      - "9001:9001"
    environment:
      - GRAPHITE_HOST=graphite
    restart: always

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"       # Web UI (Graphite dashboard)
      - "2003:2003"   # Carbon plaintext receiver (for metrics)
    restart: always